version: 2
jobs:
 base-build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Base Container
           command: |
            docker build -f Dockerfile.base -t ecohealthalliance/reservoir .
 base-build-and-deploy:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Base Container
           command: |
            docker build -f Dockerfile.base -t ecohealthalliance/reservoir .
     - deploy:
           name: Push to Docker Hub
           command: |
              docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
              docker push ecohealthalliance/reservoir
 gpu-build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build GPU Container
           command: |
            docker build -f Dockerfile.gpu -t ecohealthalliance/reservoir:gpu .
 gpu-build-and-deploy:
   machine: true
   steps:
     - checkout
     - run:
           name: Build GPU Container
           command: |
            docker build -f Dockerfile.gpu -t ecohealthalliance/reservoir:gpu .
     - deploy:
           name: Push to Docker Hub
           command: |
              docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
              docker push ecohealthalliance/reservoir:gpu

workflows:
   version: 2
   commit:
     jobs:
       - base-build
       - gpu-build
       - base-build-and-deploy:
           filters:
             branches:
               only:
                 - master
       - gpu-build-and-deploy:
           filters:
             branches:
               only:
                 - master
   weekly:
     triggers:
       - schedule:
           cron: "0 10 * * 0"
           filters:
             branches:
               only:
                 - master
     jobs:
       - base-build-and-deploy
       - gpu-build-and-deploy
